version: '3.8'

services:
  bot:
    build: .
    container_name: family_bot
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - DATABASE_URL=${DATABASE_URL}
      - TASK_TIME=${TASK_TIME}
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data  # Для SQLite файла
    restart: unless-stopped

volumes:
  logs:
  data: