version: '3.8'

services:
  bot:
    build: .
    container_name: family_bot
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - DATABASE_URL=${DATABASE_URL}
      - TASK_TIME=${TASK_TIME}
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15-alpine
    container_name: family_bot_db
    environment:
      POSTGRES_DB: family_bot
      POSTGRES_USER: bot_user
      POSTGRES_PASSWORD: bot_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bot_user -d family_bot"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data: